{{ if .Values.global.thanos.enabled }}
{{ if and .Values.bucket.enabled .Values.bucket.http.ingress.enabled }}
{{- $apiV1 := false -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- $apiV1 = true -}}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "bucket") }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.bucket.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: bucket
  {{- if .Values.bucket.http.ingress.labels }}
{{ toYaml .Values.bucket.http.ingress.labels | indent 4 }}
  {{- end }}
spec:
{{- if .Values.bucket.http.ingress.className }}
  ingressClassName: {{ .Values.ingress.bucket.http.className }}
{{- end }}
  {{- if .Values.bucket.http.ingress.tls }}
  tls:
    {{- range .Values.bucket.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.bucket.http.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        {{- if $apiV1 }}
        - path: {{ $.Values.bucket.http.ingress.path }}
          pathType: {{ $.Values.bucket.http.ingress.pathType }}
          backend:
            service:
              name: {{ include "thanos.componentname" (list $ "bucket") }}
              port:
                number: {{ $.Values.bucket.http.port }}
        {{- else }}
        - path: {{ $.Values.bucket.http.ingress.path }}
          backend:
            serviceName: {{ include "thanos.componentname" (list $ "bucket") }}
            servicePort: {{ $.Values.bucket.http.port }}
        {{- end }}
  {{- end }}
{{ end }}
{{ end }}
