{{ if .Values.global.thanos.enabled }}
{{ if and .Values.bucket.enabled .Values.bucket.http.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "bucket") }}
  {{- with .Values.bucket.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: bucket
  {{- if .Values.bucket.http.ingress.labels }}
{{ toYaml .Values.bucket.http.ingress.labels | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.bucket.http.ingress.tls }}
  tls:
    {{- range .Values.bucket.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.bucket.http.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: {{ $.Values.bucket.http.ingress.path }}
          backend:
            serviceName: {{ include "thanos.componentname" (list $ "bucket") }}
            servicePort: {{ $.Values.bucket.http.port }}
  {{- end }}
{{ end }}
{{ end }}
