---
{{ if .Values.global.thanos.enabled }}
{{- if and .Values.queryFrontend.enabled .Values.queryFrontend.http.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: query-frontend
    {{- if .Values.queryFrontend.http.ingress.labels }}
    {{ toYaml .Values.queryFrontend.http.ingress.labels | indent 4 }}
    {{- end }}
    {{- with .Values.queryFrontend.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.queryFrontend.http.ingress.tls }}
  tls:
    {{- range .Values.queryFrontend.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.queryFrontend.http.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.queryFrontend.http.ingress.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
              servicePort: {{ $.Values.queryFrontend.http.port }}
  {{- end }}
{{- end }}
{{ end }}
