---
{{ if .Values.global.thanos.enabled }}
{{- if and .Values.queryFrontend.enabled .Values.queryFrontend.http.ingress.enabled }}
{{- $apiV1 := false -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- $apiV1 = true -}}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: query-frontend
    {{- if .Values.queryFrontend.http.ingress.labels }}
    {{ toYaml .Values.queryFrontend.http.ingress.labels | indent 4 }}
    {{- end }}
    {{- with .Values.queryFrontend.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.queryFrontend.http.ingress.className }}
  ingressClassName: {{ .Values.ingress.queryFrontend.http.className }}
{{- end }}
  {{- if .Values.queryFrontend.http.ingress.tls }}
  tls:
    {{- range .Values.queryFrontend.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.queryFrontend.http.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- if $apiV1 }}
          - path: {{ $.Values.queryFrontend.http.ingress.path }}
            pathType: {{ $.Values.queryFrontend.http.ingress.pathType }}
            backend:
              service:
                name: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
                port:
                  number: {{ $.Values.queryFrontend.http.port }}
        {{- else }}
          - path: {{ $.Values.queryFrontend.http.ingress.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "query-frontend") }}-http
              servicePort: {{ $.Values.queryFrontend.http.port }}
        {{- end }}
  {{- end }}
{{- end }}
{{ end }}
