{{ if .Values.global.thanos.enabled }}
{{- if and .Values.store.enabled .Values.store.http.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "store") }}-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: store
  {{- if .Values.store.http.ingress.labels }}
  {{ toYaml .Values.store.http.ingress.labels | indent 4 }}
  {{- end }}
  {{- with .Values.store.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.store.http.ingress.tls }}
  tls:
    {{- range .Values.store.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.store.http.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: {{ $.Values.store.http.ingress.path }}
          backend:
            serviceName: {{ include "thanos.componentname" (list $ "store") }}-http
            servicePort: {{ $.Values.store.http.port }}
  {{- end }}
{{- end }}

---

  {{- if and .Values.store.enabled .Values.store.grpc.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "store") }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: store
  {{- if .Values.store.grpc.ingress.labels }}
  {{ toYaml .Values.grpc.ingress.labels | indent 4 }}
  {{- end }}
  {{- with .Values.store.grpc.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.store.grpc.ingress.tls }}
  tls:
    {{- range .Values.store.grpc.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.store.grpc.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: {{ $.Values.store.grpc.ingress.path }}
          backend:
            serviceName: {{ include "thanos.componentname" (list $ "store") }}-grpc
            servicePort: {{ $.Values.store.http.port }}
  {{- end }}
{{- end }}
{{ end }}
