{{ if .Values.global.thanos.enabled }}
{{- if and .Values.store.enabled .Values.store.http.ingress.enabled }}
{{- $apiV1 := false -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- $apiV1 = true -}}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "store") }}-http
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: store
  {{- if .Values.store.http.ingress.labels }}
  {{ toYaml .Values.store.http.ingress.labels | indent 4 }}
  {{- end }}
  {{- with .Values.store.http.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.store.http.ingress.className }}
  ingressClassName: {{ .Values.ingress.store.http.className }}
{{- end }}
  {{- if .Values.store.http.ingress.tls }}
  tls:
    {{- range .Values.store.http.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.store.http.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        {{- if $apiV1 }}
        - path: {{ $.Values.store.http.ingress.path }}
          pathType: {{ .Values.store.http.ingress.pathType }}
          backend:
            service:
              name: {{ include "thanos.componentname" (list $ "store") }}-http
              port:
                number: {{ $.Values.store.http.port }}
        {{- else }}
        - path: {{ $.Values.store.http.ingress.path }}
          backend:
            serviceName: {{ include "thanos.componentname" (list $ "store") }}-http
            servicePort: {{ $.Values.store.http.port }}
        {{- end }}
  {{- end }}
{{- end }}

---

  {{- if and .Values.store.enabled .Values.store.grpc.ingress.enabled }}
{{- $apiV1 := false -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- $apiV1 = true -}}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "store") }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: store
  {{- if .Values.store.grpc.ingress.labels }}
  {{ toYaml .Values.grpc.ingress.labels | indent 4 }}
  {{- end }}
  {{- with .Values.store.grpc.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.store.grpc.ingress.className }}
  ingressClassName: {{ .Values.ingress.store.grpc.className }}
{{- end }}
  {{- if .Values.store.grpc.ingress.tls }}
  tls:
    {{- range .Values.store.grpc.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.store.grpc.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
        {{- if $apiV1 }}
        - path: {{ $.Values.store.grpc.ingress.path }}
          pathType: {{ $.Values.store.grpc.ingress.pathType }}
          backend:
            service:
              name: {{ include "thanos.componentname" (list $ "store") }}-grpc
              port:
                number: {{ $.Values.store.grpc.port }}
        {{- else }}
        - path: {{ $.Values.store.grpc.ingress.path }}
          backend:
            serviceName: {{ include "thanos.componentname" (list $ "store") }}-grpc
            servicePort: {{ $.Values.store.grpc.port }}
        {{- end }}
  {{- end }}
{{- end }}
{{ end }}
