global:
  ## clusterId is used to identify the cluster in the FinOps Agent
  ## when using the same cluster names in different regions, we suggest appending the region to the clusterId
  clusterId: globally-unique-cluster-id
  federatedStorage:
    ## Use the existingSecret when a access key and secret is used to access the federated storage.
    ## the 'config' can be used when using assumed roles.
    ## when using the 'existingSecret' the 'config' should be commented out    
    existingSecret: ""
    config: |-
      type: AZURE
      config:
        container: kubecost-data
        storage_account: kubecost-federated-storage
finopsagent:
  enabled: true  # required, for agentOnly mode
clusterController:
  enabled: true  # optional, automated rightsizing of containers
networkCosts:
  enabled: true  # optional, daemonset- improves network cost allocations to the correct pod
aggregator:
  enabled: false
frontend:
  enabled: false
cloudCost:
  enabled: false
forecasting:
  enabled: false
localStore:
  enabled: false
mcp:
  enabled: false
