{
 "title": "Kubecost - container CPU & Memory usage(multi-cluster)",
 "description": "Visualize your kubernetes costs at the pod level.",
 "tags": [
  "utilization",
  "metrics",
  "kubecost"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_namespace_labels, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_id=~\"$cluster\"}, namespace) "
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{cluster_id=~\"$cluster\",namespace=~\"$namespace\", container!=\"POD\"}, container) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container allocation analysis",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  avg_over_time(kube_pod_container_resource_requests{resource=\"memory\",cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\"}[$__range])\n) by (cluster_id, namespace, container)"
    },
    {
     "expr": "sum(\n  avg_over_time(kube_pod_container_resource_requests{resource=\"cpu\",cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\"}[$__range])\n  or up * 0 \n) by (cluster_id, namespace, container)"
    }
   ]
  },
  {
   "title": "CPU Usage vs Requested",
   "type": "timeseries",
   "description": "CPU usage vs requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\",container!=\"\"}[10m])) by (cluster_id, namespace, container)",
     "legendFormat": "{{cluster_id}}/{{namespace}}/{{container}} (usage)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\"}) by (cluster_id, namespace, container)",
     "legendFormat": "{{cluster_id}}/{{namespace}}/{{ container }} (request)"
    }
   ]
  },
  {
   "title": "RAM Usage vs Requested",
   "type": "timeseries",
   "description": "Memory usage vs. requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(container_memory_working_set_bytes{cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\",container!=\"\"}[5m])) by (cluster_id, namespace, container)",
     "legendFormat": "{{cluster_id}}/{{namespace}}/{{ container }} (usage)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\"}) by (cluster_id, namespace, container)",
     "legendFormat": "{{cluster_id}}/{{namespace}}/{{ container }} (requested)"
    }
   ]
  },
  {
   "title": "CPU throttle percent",
   "type": "timeseries",
   "description": "Percentage of time a pod is being throttled. Values range from 0-100",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100\n  * sum by(cluster_id, namespace, container) (increase(container_cpu_cfs_throttled_periods_total{container!=\"\",cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\"}[5m]))\n  / sum by(cluster_id, namespace, container) (increase(container_cpu_cfs_periods_total{container!=\"\",cluster_id=~\"$cluster\", namespace=~\"$namespace\", container=~\"$container\", container!=\"POD\"}[5m]))",
     "legendFormat": "{{cluster_id}}/{{namespace}}/{{ container }}"
    }
   ]
  }
 ]
}