version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: disabled
  - package-ecosystem: docker
    directory: /cost-analyzer
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /cost-analyzer/charts/grafana
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /cost-analyzer/charts/prometheus
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /cost-analyzer/charts/thanos
    schedule:
      interval: weekly
