{{- if and (not .Values.agent) (not .Values.cloudAgent) }}
{{- if not (eq .Values.kubecostAggregator.deployMethod "disabled") }}

kind: Service
apiVersion: v1
metadata:
  name: {{ template "cloudCost.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cloudCost.commonLabels" . | nindent 4 }}
spec:
  selector:
{{ include "cloudCost.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    - name: tcp-api
      port: 9005
      targetPort: 9005
{{- end }}
{{- end }}