{{- if and (not .Values.agent) (not .Values.cloudAgent) }}
{{- if eq (include "aggregator.deployMethod" .) "statefulset" }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "aggregator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aggregator.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubecostAggregator.replicas }}
  serviceName: {{ template "aggregator.serviceName" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aggregator
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: aggregator
  volumeClaimTemplates:
  - metadata:
      name: persistent-configs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kubecostAggregator.persistentConfigsStorage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.kubecostAggregator.persistentConfigsStorage.storageRequest }}
  - metadata:
      name: aggregator-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kubecostAggregator.aggregatorDbStorage.storageClass }}
      resources:
        requests:
          storage:  {{ .Values.kubecostAggregator.aggregatorDbStorage.storageRequest }}
  - metadata:
      # FIXME: Should Aggregator and cost-model share the persistent-configs PV?
      # Aggregator being a statefulset makes this weird
      # In the StatefulSet config, all state should be stored in configmaps
      # (I think?) not on this specific volume, so its probably safe for each
      # replica to get its own Volume
      name: persistent-configs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kubecostAggregator.persistentConfigsStorage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.kubecostAggregator.persistentConfigsStorage.storageRequest }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aggregator
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: aggregator
      {{- with .Values.global.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
    {{- if .Values.kubecostAggregator.securityContext }}
      securityContext:
    {{- toYaml .Values.kubecostAggregator.securityContext | nindent 8 }}
    {{- else if and (.Values.global.platforms.openshift.enabled) (.Values.global.platforms.openshift.securityContext) }}
      securityContext:
    {{- toYaml .Values.global.platforms.openshift.securityContext | nindent 8 }}
    {{- else if .Values.global.securityContext }}
      securityContext:
    {{- toYaml .Values.global.securityContext | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "aggregator.serviceAccountName" . }}
      volumes:
        {{- $etlBackupBucketSecret := "" }}
        {{- if .Values.kubecostModel.federatedStorageConfigSecret }}
            {{- $etlBackupBucketSecret = .Values.kubecostModel.federatedStorageConfigSecret }}
        {{- end }}
        {{- if $etlBackupBucketSecret }}
        - name: etl-bucket-config
          secret:
            defaultMode: 420
            secretName: {{ $etlBackupBucketSecret }}
        {{- else }}
        {{- fail "Kubecost Aggregator Enterprise Config requires .Values.kubecostModel.federatedStorageConfigSecret" }}
        {{- end }}
      containers:
        {{- include "aggregator.containerTemplate" . | nindent 8 }}

        {{- if .Values.kubecostAggregator.jaeger.enabled }}
        {{ include "aggregator.jaeger.sidecarContainerTemplate" . | nindent 8 }}
        {{- end }}

    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
      {{- if .Values.kubecostAggregator.priority }}
      {{- if .Values.kubecostAggregator.priority.enabled }}
      {{- if .Values.kubecostAggregator.priority.name }}
      priorityClassName: {{ .Values.kubecostAggregator.priority.name }}
      {{- else }}
      priorityClassName: {{ template "cost-analyzer.fullname" . }}-aggregator-priority
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.kubecostAggregator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubecostAggregator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubecostAggregator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
