{{- if and (not .Values.agent) (not .Values.cloudAgent) }}

kind: Service
apiVersion: v1
metadata:
  name: {{ template "aggregator.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aggregator.commonLabels" . | nindent 4 }}
spec:
  selector:
{{ include "aggregator.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"
  ports:
    - name: tcp-api
      port: 9004
      targetPort: 9004
  {{- with .Values.kubecostAggregator.extraPorts }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
