{{- if .Values.budgetController -}}
{{- if .Values.budgetController.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: kubecost
spec:
  selector:
    {{ include "cost-analyzer.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      targetPort: 8443
{{- end -}}
{{- end -}}
