{{- if .Values.global.savedReports }}
{{- if .Values.global.savedReports.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{default "saved-report-configs" .Values.savedReportConfigmapName }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  saved-reports.json: '{{ toJson .Values.global.savedReports.reports }}'
{{- end -}}
{{- end -}}
