
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "smtp-configs" .Values.smtpConfigmapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
{{- if (((.Values.kubecostProductConfigs).smtp).config) }}
data:
  config: {{  .Values.kubecostProductConfigs.smtp.config | quote }}
{{- end -}}
