{{- if .Values.persistentVolume -}}
{{- if not .Values.persistentVolume.existingClaim -}}
{{- if .Values.persistentVolume.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  {{ end }}
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.size }}
    {{- else }}
      storage: 32.0Gi
    {{ end }}
{{- end -}}
{{- end -}}
{{- end -}}
