{{- if .Values.networkCosts -}}
{{- if .Values.networkCosts.enabled -}}
{{- if .Values.networkCosts.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-costs-config
  labels:
{{ template "cost-analyzer.networkCostsLabels" merge (dict "extraLabels" .Values.networkCosts.additionalLabels) .  }}
data:
  config.yaml: |
{{- toYaml .Values.networkCosts.config | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}