{{- if .Values.kubecostModel.federatedStorageConfig -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: federated-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  federated-store.yaml: {{ .Values.kubecostModel.federatedStorageConfig | b64enc }}
{{- end }}
