{{- if .Values.global.integrations.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubecost-integrations-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  creds.json: |-
    {
        "host": "{{ .Values.global.integrations.postgres.databaseHost }}",
        "port": "{{ .Values.global.integrations.postgres.databasePort }}",
        "databaseName": "{{ .Values.global.integrations.postgres.databaseName }}",
        "user": "{{ .Values.global.integrations.postgres.databaseUser }}",
        "password": "{{ .Values.global.integrations.postgres.databasePassword }}"
    }
{{- end }}
