{{- if .Values.agent }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kubecost.agentStoreSecretName" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  object-store.yaml: {{ .Values.agentKey }}
{{- end }}
