{{- if .Values.clusterController.actionConfigs.clusterRightsize }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  cluster-controller-continuous-cluster-sizing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  config: |
{{- toJson .Values.clusterController.clusterRightsize | nindent 4 }}
{{- end }}
{{- if .Values.clusterController.actionConfigs.clusterRightsize }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  cluster-controller-continuous-cluster-sizing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  config: |
{{- toJson .Values.clusterController.clusterRightsize | nindent 4 }}
{{- end }}