{{- if .Values.clusterController.actionConfigs.clusterRightsize }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  cluster-controller-continuous-cluster-sizing
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
binaryData:
  config: |
{{- toJson .Values.clusterController.actionConfigs.clusterRightsize | b64enc | nindent 4 }}
{{- end }}
---
{{- if .Values.clusterController.actionConfigs.namespaceTurndown }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  cluster-controller-nsturndown-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
binaryData:
{{- range .Values.clusterController.actionConfigs.namespaceTurndown }}
  {{ .name }}: |
      {{- toJson . | b64enc | nindent 4 }}
{{- end }}
{{- end }}
---
{{- if .Values.clusterController.actionConfigs.containerRightsize }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  cluster-controller-container-rightsizing-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
binaryData:
  config: |
{{- toJson .Values.clusterController.actionConfigs.containerRightsize | b64enc | nindent 4 }}
{{- end }}