{{- if .Values.saml }}
{{- if and .Values.saml.authSecret .Values.saml.authSecretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.saml.authSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
stringData:
  clientSecret: {{ .Values.saml.authSecret }}
{{- end -}}
{{- end -}}
