{{- if .Values.kubecostAdmissionController -}}
{{- if .Values.kubecostAdmissionController.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: {{.Release.Namespace}}
spec:
  selector:
    {{- include "cost-analyzer.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      targetPort: 8443
{{- end -}}
{{- end -}}
