{{- if .Values.global.mimirProxy }}
{{- if .Values.global.mimirProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-mimir-proxy
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: mimir-proxy
      protocol: TCP
      port: {{ .Values.global.mimirProxy.port }}
      targetPort: {{ .Values.global.mimirProxy.port }}
  selector:
    app: mimir-proxy
  type: ClusterIP
{{- end }}
{{- end }}