{{- if .Values.global.mimirProxy }}
{{- if .Values.global.mimirProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-mimir-proxy
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen {{ .Values.global.mimirProxy.port }};
        location / {
          proxy_pass  {{ .Values.global.mimirProxy.mimirEndpoint }};
          proxy_set_header  X-Scope-OrgID "{{ .Values.global.mimirProxy.orgIdentifier }}";
          {{- if .Values.global.mimirProxy.basicAuth }}
          proxy_set_header  Authorization "Basic {{ (printf "%s:%s" .Values.global.mimirProxy.basicAuth.username .Values.global.mimirProxy.basicAuth.password) | b64enc }}";
          {{- end }}
        }
    }
{{- end }}
{{- end }}
