{{- if .Values.networkCosts }}
{{- if .Values.networkCosts.enabled }}
{{- if .Values.networkCosts.podSecurityPolicy }}
{{- if or (.Values.networkCosts.podSecurityPolicy.enabled) (.Values.global.platforms.openshift.scc.networkCosts) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-network-costs
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
  annotations:
  {{- with .Values.networkCosts.podSecurityPolicy.annotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ template "cost-analyzer.fullname" . }}-network-costs
{{- if .Values.global.platforms.openshift.scc.networkCosts }}
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - {{ template "cost-analyzer.networkCostsName" . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
