{{ if .Values.global.prometheus.enabled }}
{{- if .Values.prometheus.pushgateway.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "prometheus.pushgateway.fullname" . }}
  labels:
    {{- include "prometheus.pushgateway.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.prometheus.pushgateway.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "prometheus.pushgateway.labels" . | nindent 6 }}
{{- end }}
{{ end }}
