{{- if and (not .Values.agent) (not .Values.cloudAgent) (.Values.kubecostQueryHandler) }}
{{- if gt (.Values.kubecostQueryHandler.replicas | toString | atoi) 0 }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "queryhandler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "queryhandler.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kubecostQueryHandler.replicas }}
  serviceName: "queryhandler"
  selector:
    matchLabels:
      app.kubernetes.io/name: queryhandler
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: queryhandler
  volumeClaimTemplates:
  - metadata:
      name: persistent-configs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kubecostQueryHandler.persistentConfigsStorage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.kubecostQueryHandler.persistentConfigsStorage.storageRequest }}
  - metadata:
      name: queryhandler-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kubecostQueryHandler.queryHandlerStorage.storageClass }}
      resources:
        requests:
          storage:  {{ .Values.kubecostQueryHandler.Storage.storageRequest }}
  {{- if .Values.kubecostQueryHandler.queryHandlerDbStorage }}
  - metadata:
      name: queryhandler-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.kubecostQueryHandler.queryHandlerDbStorage.storageClass }}
      resources:
        requests:
          storage:  {{ .Values.kubecostQueryHandler.queryHandlerDbStorage.storageRequest }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: queryhandler
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: queryhandler
    spec:
      restartPolicy: Always
      serviceAccountName: {{ template "queryhandler.serviceAccountName" . }}
      volumes:
        {{- $etlBackupBucketSecret := "" }}
        {{- if .Values.kubecostModel.federatedStorageConfigSecret }}
            {{- $etlBackupBucketSecret = .Values.kubecostModel.federatedStorageConfigSecret }}
        {{- end }}
        {{- if $etlBackupBucketSecret }}
        - name: bucket-config
          secret:
           defaultMode: 420
           secretName: {{ $etlBackupBucketSecret }}
        {{- end }}
      initContainers:
        - name: config-db-perms-fix
          image: busybox
          command: ["sh", "-c", "/bin/chmod -R 777 /var/configs"]
          volumeMounts:
            - name: persistent-configs
              mountPath: /var/configs
            - name: queryhandler-storage
              mountPath: /var/configs/waterfowl
            {{- if .Values.kubecostQueryHandler.queryHandlerDbStorage }}
            - name: queryhandler-db-storage
              mountPath: /var/configs/waterfowl/duckdb
            {{- end }}
          securityContext:
            runAsUser: 0
      containers:
        - name: queryhandler
          {{- if .Values.kubecostModel }}
          {{- if .Values.kubecostModel.openSourceOnly }}
          {{- fail "Kubecost Query Handler cannot be used with open source only" }}
          {{- else if .Values.kubecostQueryHandler.fullImageName }}
          image: {{ .Values.kubecostQueryHandler.fullImageName }}
          {{- else if .Values.kubecostModel.fullImageName }}
          image: {{ .Values.kubecostModel.fullImageName }}
          {{- else if .Values.imageVersion }}
          image: {{ .Values.kubecostModel.image }}:{{ .Values.imageVersion }}
          {{- else }}
          image: {{ .Values.kubecostModel.image }}:prod-{{ $.Chart.AppVersion }}
          {{ end }}
          {{- else }}
          image: gcr.io/kubecost1/cost-model:prod-{{ $.Chart.AppVersion }}
          {{ end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9004
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 200
          imagePullPolicy: Always
          args: ["waterfowl"]
          ports:
            - name: tcp-api
              containerPort: 9004
              protocol: TCP
          resources:
{{ toYaml .Values.kubecostQueryHandler.resources | indent 12 }}
          volumeMounts:
            - name: persistent-configs
              mountPath: /var/configs
            - name: bucket-config
              mountPath: /var/configs/etl
            - name: queryhandler-storage
              mountPath: /var/configs/waterfowl
            {{- if .Values.kubecostQueryHandler.queryHandlerDbStorage }}
            - name: queryhandler-db-storage
              mountPath: /var/configs/waterfowl/duckdb
            {{- end }}
          env:
            {{- if and (.Values.prometheus.server.global.external_labels.cluster_id) (not .Values.prometheus.server.clusterIDConfigmap) }}
            - name: CLUSTER_ID
              value: {{ .Values.prometheus.server.global.external_labels.cluster_id }}
            {{- end }}
            {{- if .Values.prometheus.server.clusterIDConfigmap }}
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.prometheus.server.clusterIDConfigmap }}
                  key: CLUSTER_ID
            {{- end }}

            - name: CONFIG_PATH
              value: /var/configs/
            - name: ETL_ENABLED
              value: "false" # this pod should never run KC's concept of "ETL"
            - name: CLOUD_PROVIDER_API_KEY
              value: "AIzaSyDXQPG_MHUEy9neR7stolq6l0ujXmjJlvk" # The GCP Pricing API key.This GCP api key is expected to be here and is limited to accessing google's billing API.'
              value: "true" # just in case, not sure if necessary

            {{- if $etlBackupBucketSecret }}
            # If this isn't set, we pretty much have to be in a read only state,
            # initialization will probably fail otherwise.
            - name: ETL_BUCKET_CONFIG
              {{- if not .Values.kubecostModel.federatedStorageConfigSecret}}
              value: "/var/configs/etl/object-store.yaml"
              {{- else  }}
              value: "/var/configs/etl/federated-store.yaml"
            - name: FEDERATED_STORE_CONFIG
              value: "/var/configs/etl/federated-store.yaml"
            - name: FEDERATED_PRIMARY_CLUSTER # this ensures the ingester runs assuming federated primary paths in the bucket
              value: "true"
            - name: FEDERATED_CLUSTER # this ensures the ingester runs assuming federated primary paths in the bucket
              value: "true"
              {{- end }}
            {{- end }}

            # TODO (michaelmdresser):
            # - SAML configs?
            # - Product key configs?

            {{- range $key, $value := .Values.kubecostQueryHandler.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: KUBECOST_NAMESPACE
              value: {{ .Release.Namespace }}

    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
      {{- if .Values.kubecostQueryHandler.priority }}
      {{- if .Values.kubecostQueryHandler.priority.enabled }}
      {{- if .Values.kubecostQueryHandler.priority.name }}
      priorityClassName: {{ .Values.kubecostQueryHandler.priority.name }}
      {{- else }}
      priorityClassName: {{ template "cost-analyzer.fullname" . }}-queryhandler-priority
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.kubecostQueryHandler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubecostQueryHandler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubecostQueryHandler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
