{{ if .Values.global.prometheus.enabled }}
{{- if and .Values.nodeExporter.enabled .Values.rbac.create }}
{{- if or (default .Values.nodeExporter.podSecurityPolicy.enabled false) (.Values.podSecurityPolicy.enabled) (.Values.global.platforms.openshift.scc.nodeExporter) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "prometheus.nodeExporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.nodeExporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "prometheus.nodeExporter.fullname" . }}
{{- if .Values.global.platforms.openshift.scc.nodeExporter }}
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs: ['use']
  resourceNames:
  - {{ template "prometheus.nodeExporter.fullname" . }}
{{- end }}
{{- end }}
{{- end }}
{{ end }}
