name: "Feature Request"
description: Suggest a new feature for the Kubecost chart. Please read the ISSUE_GUIDELINES.md file to determine what is an appropriate feature request for this repository.
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please explain the feature you'd like to see in the Kubecost Helm chart.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem.
      placeholder: A clear and concise description of the problem statement.
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution Description
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
      # value: "asdf"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
      # value: "asdf"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context to this enhancement request.
      placeholder: Add any other context or screenshots about the feature request here.
      # value: "asdf"
    validations:
      required: false
  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: >-
        By submitting this issue, you agree to the following.
      options:
        - label: I have read and followed the [issue guidelines](ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
          required: true
        - label: I have searched other issues in this repository and mine is not recorded.
          required: true
