# TurndownSchedule Custom Resource Definition for persistence
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: turndownschedules.kubecost.com
spec:
  group: kubecost.com
  names:
    kind: TurndownSchedule
    singular: turndownschedule
    plural: turndownschedules
    shortNames:
    - td
    - tds
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                start:
                  type: string
                  format: date-time
                end:
                  type: string
                  format: date-time
                repeat:
                  type: string
                  enum: [none, daily, weekly]
            status:
              type: object
              properties:
                state:
                  type: string
                lastUpdated:
                  format: date-time
                  type: string
                current:
                  type: string
                scaleDownId:
                  type: string
                nextScaleDownTime:
                  format: date-time
                  type: string
                scaleDownMetadata:
                  additionalProperties:
                    type: string
                  type: object
                scaleUpID:
                  type: string
                nextScaleUpTime:
                  format: date-time
                  type: string
                scaleUpMetadata:
                  additionalProperties:
                    type: string
                  type: object
      additionalPrinterColumns:
      - name: State
        type: string
        description: The state of the turndownschedule
        jsonPath: .status.state
      - name: Next Turndown
        type: string
        description: The next turndown date-time
        jsonPath: .status.nextScaleDownTime
      - name: Next Turn Up
        type: string
        description: The next turn up date-time
        jsonPath: .status.nextScaleUpTime
