kubecostProductConfigs:
  clusterName: CLUSTER_NAME
  # cloudIntegrationSecret: cloud-integration
federatedETL:
  useExistingS3Config: false
  federatedCluster: true
kubecostModel:
  containerStatsEnabled: true
  cloudCost:
    enabled: true  # Set to true to enable CloudCost view that gives you visibility of your Cloud provider resources cost
  etlCloudAsset: false  # Set etlCloudAsset to false when cloudCost.enabled=true
  federatedStorageConfigSecret: federated-store
serviceAccount:  # this example uses AWS IRSA, which creates a service account with rights to the s3 bucket. If using keys+secrets in the federated-store, set create: true
  create: true
global:
  prometheus:
    enabled: true
    # fqdn: http://prometheus-operated.monitoring:9090
  grafana:  # prometheus metrics will be local cluster only, disable grafana to save resources
    enabled: false
    proxy: false
prometheus:
  nodeExporter:
    enabled: false
  server:
    global:
      external_labels:
        # cluster_id should be unique for all clusters and the same value as .kubecostProductConfigs.clusterName
        cluster_id: CLUSTER_NAME
networkCosts:
  # optional, see: https://docs.kubecost.com/install-and-configure/advanced-configuration/network-costs-configuration
  enabled: true
  config:
    services:
      # set the appropriate cloud provider to true
      amazon-web-services: true
      # google-cloud-services: true
      # azure-cloud-services: true
