{{ if .Values.global.prometheus.enabled }}
{{- if and .Values.prometheus.nodeExporter.enabled .Values.prometheus.serviceAccounts.nodeExporter.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.nodeExporter.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.nodeExporter" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{ end }}
