{{ if .Values.global.prometheus.enabled }}
{{- if .Values.prometheus.server.enabled -}}
{{- if .Values.prometheus.serviceAccounts.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.serviceAccountName.server" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.prometheus.serviceAccounts.server.annotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{ end }}
