{
 "title": "Pod utilization metrics",
 "tags": [
  "kubecost",
  "cost",
  "utilization",
  "metrics"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace) "
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"}, pod) "
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$pod\", container!=\"POD\"}, container) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Core Usage vs Requested",
   "type": "timeseries",
   "description": "Maximum CPU Core Usage vs Requested",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(\r\n  container_cpu_usage_seconds_total\r\n    {namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}\r\n    [$__rate_interval])) \r\n    by (cluster_id, namespace, pod, container)",
     "legendFormat": "{{cluster_id}} {{pod}}/{{container}} (usage max)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests\r\n  {resource=\"cpu\",unit=\"core\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}\r\n  ) \r\nby (cluster_id, namespace, pod, container)",
     "legendFormat": "{{cluster_id}} {{pod}}/{{container}} (avg requested)"
    }
   ]
  },
  {
   "title": "Memory Usage vs Requested",
   "type": "timeseries",
   "description": "Max Memory usage vs avg requested",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(\r\n  container_memory_working_set_bytes\r\n  {namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\",container!=\"\"}\r\n  [$__rate_interval])) \r\nby (cluster_id,namespace,pod,container)",
     "legendFormat": "{{cluster_id}} {{pod}}/{{container}} (usage max)"
    },
    {
     "expr": "avg(\n  kube_pod_container_resource_requests\n  {resource=\"memory\",unit=\"byte\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\", container!=\"POD\"}\n  )\nby (cluster_id,namespace,pod,container)",
     "legendFormat": "{{cluster_id}} {{pod}}/{{container}} (avg requested)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "description": "Network traffic by pod",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total\n  {namespace=~\"$namespace\",pod=~\"$pod\"}\n  [$__rate_interval])) \nby (cluster_id, namespace, pod)",
     "legendFormat": "{{cluster_id}} {{namespace}}/{{pod}}<- in"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total\n  {namespace=~\"$namespace\",pod=~\"$pod\"}\n  [$__rate_interval])) \nby (cluster_id, namespace, pod)",
     "legendFormat": "{{cluster_id}} {{namespace}}/{{pod}}-> out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "Disk read writes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total\r\n    {container!=\"POD\",pod!=\"\",pod=~\"$pod\",container=~\"$container\"}\r\n     [$__rate_interval])) \r\nby (cluster_id,namespace,pod,container)",
     "legendFormat": "{{cluster_id}} {{pod}}/{{container}}<- write"
    },
    {
     "expr": "- sum(irate(container_fs_reads_bytes_total\r\n     {container!=\"POD\",pod!=\"\",pod=~\"$pod\",container=~\"$container\"}\r\n     [$__rate_interval])) \r\nby (cluster_id,namespace,pod,container)",
     "legendFormat": "{{cluster_id}} {{pod}}/{{container}}-> read"
    }
   ]
  },
  {
   "title": "CPU throttle percent",
   "type": "timeseries",
   "description": "This graph shows the % of periods where a pod is being throttled. Values range from 0-100",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100\n  * sum by(cluster_id, namespace, pod, container) (increase(container_cpu_cfs_throttled_periods_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__rate_interval]))\n  / sum by(cluster_id, namespace, pod, container) (increase(container_cpu_cfs_periods_total{container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}