
apiVersion: v2
appVersion: "1.89.0-rc.2"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.89.0-rc.2
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
dependencies:
  - name: grafana
    repository: file://./charts/grafana
  - name: prometheus
    repository: file://./charts/prometheus
  - name: thanos
    repository: file://./charts/thanos
