apiVersion: v2
appVersion: "1.92.0"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: "1.92.0"
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
dependencies:
  - condition: global.grafana.enabled
    name: grafana
    repository: file://./charts/grafana
  - condition: global.prometheus.enabled
    name: prometheus
    repository: file://./charts/prometheus
  - condition: global.thanos.enabled
    name: thanos
    repository: file://./charts/thanos
