{
 "title": "Workload Metrics",
 "description": "Most used metrics when troubleshooting applications",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_owner{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_working_set_bytes{container=~\"$container\",pod=~\"$pod\",container!=\"\",namespace=~\"$namespace\"} ) by (namespace,pod,container))",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Top CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, (\r\n    sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[10m])) by (namespace,pod,container)\r\n    )\r\n)",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Kubecost Top Network (egress is negative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(topk(5,\n    rate(kubecost_pod_network_ingress_bytes_total\n        {namespace=~\"$namespace\", pod_name=~\"$pod\"}\n        [$__rate_interval]\n    )\n) )\nby(namespace, pod_name) ",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    },
    {
     "expr": "- sum(topk(5,\n    rate(kubecost_pod_network_egress_bytes_total\n        {namespace=~\"$namespace\", pod_name=~\"$pod\"}\n        [$__rate_interval]\n    )\n) )\nby(namespace, pod_name) ",
     "legendFormat": "{{namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "Top Network (transmit is negative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(topk(5,rate(container_network_receive_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))) by (namespace,pod) ",
     "legendFormat": "{{namespace}}/{{pod}}"
    },
    {
     "expr": "-sum(topk(5,rate(container_network_transmit_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))) by (namespace,pod) ",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Storage (read is negative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "\n sum(rate(container_fs_writes_bytes_total\n  {pod=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}\n  [$__rate_interval]))\n by (namespace,pod,container)\n>0 ",
     "legendFormat": "{{namespace}}/{{container}}"
    },
    {
     "expr": "-(sum\r\n (rate(container_fs_reads_bytes_total\r\n  {pod=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}\r\n  [$__rate_interval])) \r\nby (namespace,pod,container) \r\n) <0",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  },
  {
   "title": "Storage ",
   "type": "timeseries",
   "description": "This may work depending on the CRI",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}) by (namespace,persistentvolumeclaim)",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod restarts per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"}[1h])) by (namespace,container)>0",
     "legendFormat": "{{namespace}}/{{container}}"
    }
   ]
  }
 ]
}