global:
  amp:
    enabled: true
    prometheusServerEndpoint: http://localhost:8005/workspaces/$<AMP_WORKSPACE_ID>
    remoteWriteService: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/$<AMP_WORKSPACE_ID>/api/v1/remote_write
    sigv4:
      region: us-west-2

sigV4Proxy:
  region: us-west-2
  host: aps-workspaces.us-west-2.amazonaws.com

kubecostProductConfigs:
  clusterName: AWS-cluster-one

prometheus:
  server:
    global:
      external_labels:
        cluster_id: AWS-cluster-one