name: Close stale issues and PRs
on:
  schedule:
    - cron: '30 1 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: This issue has been marked as stale because it has been open for 360 days with no activity. Please remove the stale label or comment or this issue will be closed in 5 days.
          close-issue-message: This issue was closed because it has been inactive for 365 days with no activity.
          stale-pr-message: This pull request has been marked as stale because it has been open for 90 days with no activity. Please remove the stale label or comment or this pull request will be closed in 5 days.
          close-pr-message: This pull request was closed because it has been inactive for 95 days with no activity.
          days-before-issue-stale: 230
          days-before-issue-close: 5
          days-before-pr-stale: 90
          days-before-pr-close: 5
